version: '3.8'

services:
  wordpress:
    image: wordpress:6.5-php8.2
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_CONFIG_EXTRA: |
        define ('WP_ENV', 'development');
    volumes:
      - ./wp:/var/www/html
      - .:/var/www/html/wp-content/themes/tincho-base-theme:cached

  db:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: wp
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
